spring:
  config:
    activate:
      # Profile expressions that should match for the document to be included.
      # 수록될 문서와 맞는 프로필 표현
      on-profiles: mysql

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study_board?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: